font_family Iosevka Curly
bold_font auto
italic_found auto
font_size 13.0

cursor_shape underline
cursor_blink yes

scrollback_lines 1000

# disable_ligatures_in active always

map ctrl+minus change_font_size all -2.0
map ctrl+equal change_font_size all +2.0
map ctrl+backspace change_font_size all 0
map ctrl+c copy_and_clear_or_interrupt
map ctrl+s kitten scrollback

sync_to_monitor no
confirm_os_window_close 0

enable_audio_bell yes
visual_bell_duration 0.5
visual_bell_color blue
window_alert_on_bell yes
command_on_bell sh -c 'notify-send "BELL :3" "$KITTY_CHILD_CMDLINE wants your attention!"'
