[ids]

*

[global]

default_layout = main

[main]

capslock = overload(control, escape)
scrolllock = compose
compose = layer(3alt)

[gaming:layout]

capslock = insert

[3alt]

shift = layer(shift3alt)

a = macro(compose " a)
4 = macro(compose o a)
c = macro(compose c c)
e = macro(compose a e)
o = macro(compose " o)
0 = macro(compose ~ o)
/ = macro(compose / o)
s = macro(compose c s)
5 = macro(compose s s)
u = macro(compose " u)
z = macro(compose c z)

f1 = setlayout(main)
f2 = setlayout(gaming)

[shift3alt]

a = macro(compose " A)
4 = macro(compose o A)
c = macro(compose c C)
e = macro(compose A E)
o = macro(compose " O)
0 = macro(compose ~ O)
/ = macro(compose / O)
s = macro(compose c S)
5 = macro(compose S S)
u = macro(compose " U)
z = macro(compose c Z)
