set -g status off

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix
set -g escape-time 0

set -g status-style "bg=black, fg=white"
set -g default-terminal "tmux-256color"
# set -g terminal-overrides "*:smcup@:rmcup@"
# set -sa terminal-overrides ',xterm*:Ss=\E[%p1%d q:Se=\E[4 q'
set -ga terminal-overrides ",xterm*:Ss=\e[0 q:Se=\e[0 q"
set -as terminal-features 'xterm-kitty:cstyle'

# bind-key e run-shell "tmux capture-pane -pS -1000 | nvim -"
